import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HTMLLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-white border-b flex items-center px-5">
          <Link className="font-bold text-2xl pb-3 pt-3" href="#">발랑</Link>
          <Link href="/brands" className="ml-20">BRANDS</Link>
          
          <div className="ml-auto flex items-center gap-x-5">
          <button className="font-medium">회원가입</button>
          <button className="">로그인</button>
          </div>
        </header>
      {children}
      </body>
    </html>
  );
}
